version: '3.7'

services:

# ======================================================================
# Load Balance | 80, 443
# ======================================================================

  lb1:
    image: nginx:1.15.4-alpine
    container_name: tsms-lb1
    restart: always
    environment:
      - VIRTUAL_HOST=tsms.in.th
      - VIRTUAL_PORT=80
      - VIRTUAL_PORT=443
      - NGINX_HOST=tsms.in.th
      - NGINX_PORT=80
      - NGINX_PORT=443
      - TERM=xterm
    volumes:
      - ./balance/conf.d:/etc/nginx/conf.d
      - ./balance/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend_network

# ======================================================================
# Database | 2000
# ======================================================================

  sql1:
    image: mariadb:10.3.9
    container_name: tsms-sql1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd@61++
      - VIRTUAL_PORT=2100
      - TERM=xterm
    volumes:
      - ./database/sql1:/var/lib/mysql
    ports:
      - "2100:3306"
    networks:
      - database_network

  mongo1:
    image: mongo:4.1.3
    container_name: tsms-mongo1
    restart: always
    environment:
      - VIRTUAL_PORT=2200
      - TERM=xterm
      - AUTH=yes
    volumes:
      - ./database/mongo1:/data/db
    ports:
      - "2200:27017"
    networks:
      - database_network
    command: mongod

  pma1:
    image: phpmyadmin/phpmyadmin:4.8.3
    container_name: tsms-pma1
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=P@ssw0rd@61++
      - VIRTUAL_PORT=2999
      - TERM=xterm
    links:
      - "sql1:mariadb"
    ports:
      - "2999:80"
    networks:
      - database_network

# ======================================================================
# PHP 7 + Phalcon | 9000
# ======================================================================

  php7fpm1:
    image: codestep/php7phalcon:7.2.10
    container_name: tsms-php7fpm1
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_HOST=tsms.in.th
      - VIRTUAL_PORT=9001
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./webserver/conf.d/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9001:9000"
    links:
      - "mongo1:mongo"
      - "sql1:mysql"
    networks:
      - frontend_network
      - database_network

# ======================================================================
# Web Server | 8000
# ======================================================================

  main1:
    image: nginx:1.15.4-alpine
    container_name: tsms-main1
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_HOST=tsms.in.th
      - VIRTUAL_PORT=8100
      - NGINX_HOST=tsms.in.th
      - NGINX_PORT=80
      - TERM=xterm
    volumes:
      - ./www/main.tsms.in.th:/usr/share/nginx/html/main.tsms.in.th
      - ./webserver/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/sites/main1.tsms.in.th.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm1:phpfpm"
    ports:
      - "8100:80"
    networks:
      - frontend_network
      - database_network

  core1:
    image: nginx:1.15.4-alpine
    container_name: tsms-core1
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - VIRTUAL_HOST=core.tsms.in.th
      - VIRTUAL_PORT=8200
      - NGINX_HOST=core.tsms.in.th
      - NGINX_PORT=80
      - TERM=xterm
    volumes:
      - ./www/core.tsms.in.th:/usr/share/nginx/html/core.tsms.in.th
      - ./webserver/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/sites/core1.tsms.in.th.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm1:phpfpm"
    ports:
      - "8200:80"
    networks:
      - frontend_network
      - database_network

networks:
  frontend_network:
    name: frontend_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
  database_network:
    name: database_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24